/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_epicport_glue_NativeGlue */

#ifndef _Included_com_epicport_glue_NativeGlue
#define _Included_com_epicport_glue_NativeGlue
#ifdef __cplusplus
extern "C" {
#endif
#undef com_epicport_glue_NativeGlue_MIN_PRIORITY
#define com_epicport_glue_NativeGlue_MIN_PRIORITY 1L
#undef com_epicport_glue_NativeGlue_NORM_PRIORITY
#define com_epicport_glue_NativeGlue_NORM_PRIORITY 5L
#undef com_epicport_glue_NativeGlue_MAX_PRIORITY
#define com_epicport_glue_NativeGlue_MAX_PRIORITY 10L
#undef com_epicport_glue_NativeGlue_GM_UNKNOWN
#define com_epicport_glue_NativeGlue_GM_UNKNOWN 0L
#undef com_epicport_glue_NativeGlue_GM_IN_GAME
#define com_epicport_glue_NativeGlue_GM_IN_GAME 1L
/*
 * Class:     com_epicport_glue_NativeGlue
 * Method:    gameMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_epicport_glue_NativeGlue_gameMode
  (JNIEnv *, jclass);

/*
 * Class:     com_epicport_glue_NativeGlue
 * Method:    buyResource
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_epicport_glue_NativeGlue_buyResource
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
